services:
  - type: web
    name: gunaflow-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn GunaFlow.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
